package com.modernpatriot.reimaginedindustries.core;

public class WIP {

	//  F L U I D S
	
	/* MOLTEN LUX
	 * CONDENSED AIR
	 * SINISTER GLUE
	 * OXIDIZED PAIN
	 * METALLIC TINT
	 * GLOWING ICE
	 * GOLDEN PURIFIER
	 * VAPORIZED SKY
	 * PLANT ESSENCE
	 * STEAM
	*/
	
	//  I T E M S
	
	/* POISONED HAIRPIN
	 * RING OF THE OPEN-MINDED
	 * BROOCH OF THE LOST SOULS
	 * AMULET OF THE BROKEN HEARTED
	 * CHARM OF THE THOUSAND ISLANDS
	 * SPIKED ROSARY
	 * LOCKET OF SHADOWS
	 * TINKERS POCKETWATCH
	 * CROWN OF THE FALLEN EMPIRE
	 * PORTABLE LINKING CHAMBER
	 * BOMB IN A BOTTLE
	 * SOFT DYNAMITE
	 * SHINING CRYSTAL
	 * ICY CRYSTAL
	 * GOLDEN NEEDLE
	 * BLAZING NEEDLE
	 * DARK NEEDLE
	 * PORTABLE VOID
	 * COMPASS OF THE BLIND HERMIT
	 * DARK AURA SHARD
	 * HOLY AURA SHARD
	 * CRUEL BEHEADER
	 * ARMOR FOR PLATINUM, TUNGSTEN, ZIRCALLOY, CHROME, MANGANESE
	 * TOOLS FOR PLATINUM, ZIRCALLOY, CHROME
	*/
	
	//  B L O C K S
	
	/* HYPERMAGNETIC TESLA
	 * PRISMATIC BLOCKS
	 * SENSITIVE COMPACTOR
	 * RISING GRAND PIANO
	 * UNSTABLE TANK
	 * STABILIZED TANK
	 * LOST CONDENSER (1mB/sec)
	*/
	
	//  R I T U A L S
	
	/* RITUAL OF STABILITY
	 * RITUAL OF THE THOUSAND SEAS
	 * RITUAL OF THE EVERLASTING DARKNESS
	 * RITUAL OF THE EVERLASTING LIGHT
	 * RITUAL OF POSESSION
	 * RITUAL OF THE MOLTEN CORE
	 * RITUAL OF THE DYING SPIRIT
	 */
	
	//  M U L T I B L O C K S
	
	/* SIMPLE FIREBOX
	 * SINISTER FIREBOX
	 * STEAMPOWERED FIREBOX
	 * TINKERS WORKTABLE TIER 1
	 * TINKERS WORKTABLE TIER 2
	 * INFUSER
	 */
	
	//  B U G S   /   W I P
	
	/* SERVER DOESNT SEND PACKETS FOR INVENTORY CONTENT ON PLAYER JOIN
	 * NOT ENOUGH ITEMS DOESNT REGISTER THE MOD
	 */
	 
}
